; Listing generated by Microsoft (R) Optimizing Compiler Version 19.36.32537.0 

	TITLE	C:\Users\maste\source\repos\Task1.2_FIS\Debug\Task1.2_FIS.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__BCE9A664_concurrencysal@h DB 01H
__3A60702B_sal@h DB 01H
__230315B8_vadefs@h DB 01H
__37F021F1_vcruntime@h DB 01H
__D32D64EC_xkeycheck@h DB 01H
__0E563EE6_yvals_core@h DB 01H
__E57855E1_limits@h DB 01H
__3FE9B7C5_climits DB 01H
__04C75F1C_corecrt@h DB 01H
__F142ABC1_vcruntime_new@h DB 01H
__1DDEC634_vcruntime_new_debug@h DB 01H
__8CF369C8_crtdbg@h DB 01H
__DC312741_crtdefs@h DB 01H
__1DC7F6AB_use_ansi@h DB 01H
__0D462388_yvals@h DB 01H
__92857972_corecrt_math@h DB 01H
__A29DED85_math@h DB 01H
__494656A0_corecrt_malloc@h DB 01H
__0C5B3DCC_stddef@h DB 01H
__F1F53BCE_corecrt_search@h DB 01H
__DD5AA43A_corecrt_wstdlib@h DB 01H
__71F46169_stdlib@h DB 01H
__BB069537_cstdlib DB 01H
__E6C9C4E2_xtr1common DB 01H
__E1673D43_intrin0@inl@h DB 01H
__C51C9E4A_intrin0@h DB 01H
__58DA7E9C_cmath DB 01H
__C44F8F6B_corecrt_stdio_config@h DB 01H
__A7F89B2B_corecrt_wstdio@h DB 01H
__B5C48800_stdio@h DB 01H
__99C665A7_cstdio DB 01H
__15E49872_errno@h DB 01H
__F9D87D4D_vcruntime_string@h DB 01H
__184F7456_corecrt_memcpy_s@h DB 01H
__82377222_corecrt_memory@h DB 01H
__5B29309E_corecrt_wstring@h DB 01H
__F787F5CD_string@h DB 01H
__F7943DD7_cstring DB 01H
__E387ED1C_corecrt_wconio@h DB 01H
__78D0C915_corecrt_wctype@h DB 01H
__02A4DD57_corecrt_wdirect@h DB 01H
__A056EFF3_corecrt_share@h DB 01H
__91FC0EDF_corecrt_wio@h DB 01H
__6619318A_corecrt_wprocess@h DB 01H
__18070508_corecrt_wtime@h DB 01H
__3D2AFB26_types@h DB 01H
__72103B05_stat@h DB 01H
__4BE26BFD_wchar@h DB 01H
__034DB3F4_cwchar DB 01H
__1ECD4F9A_cstddef DB 01H
__A62FD057_initializer_list DB 01H
__7B1487AE_xstddef DB 01H
__408D36C2_iosfwd DB 01H
__5B0E7BDE_stdint@h DB 01H
__0658744A_cstdint DB 01H
__9D84A227_type_traits DB 01H
__8C0B10BC_utility DB 01H
__EA0F6671___msvc_iter_core@hpp DB 01H
__37D60323_xutility DB 01H
__267AB463_iterator DB 01H
__83BF90D8_share@h DB 01H
__41DD709E___msvc_system_error_abi@hpp DB 01H
__04E7115C_cerrno DB 01H
__E5D9469F_malloc@h DB 01H
__C78E68C1_corecrt_terminate@h DB 01H
__F2721FE7_eh@h DB 01H
__1530C366_vcruntime_exception@h DB 01H
__146E49D7_exception DB 01H
__CDB0EEF0_float@h DB 01H
__EA82AE20_cfloat DB 01H
__2A53773E_isa_availability@h DB 01H
__8C64E344_limits DB 01H
__BB53D1C7_new DB 01H
__1E62C501_xatomic@h DB 01H
__E69E737F_xmemory DB 01H
__CAABAF75___msvc_sanitizer_annotate_container@hpp DB 01H
__924DF5E3_xstring DB 01H
__9D20738A_stdexcept DB 01H
__4DCEE0B6_xcall_once@h DB 01H
__A5D33687_xerrc@h DB 01H
__93FD7E51_time@h DB 01H
__9E69E294_ctime DB 01H
__8112E062_xtimec@h DB 01H
__7C89C118_xthreads@h DB 01H
__E751BF86_atomic DB 01H
__F293F296_system_error DB 01H
__FEE180EE_vcruntime_typeinfo@h DB 01H
__4709F03A_typeinfo DB 01H
__30CAEFCA_memory DB 01H
__1C8FB8C5_xfacet DB 01H
__1C9D888F___msvc_xlocinfo_types@hpp DB 01H
__6AECDA3E_ctype@h DB 01H
__960D8200_cctype DB 01H
__66B29864_locale@h DB 01H
__28AA49E6_clocale DB 01H
__588013F2_xlocinfo DB 01H
__4D7381D2_xlocale DB 01H
__616564E1_xiosbase DB 01H
__9F80CB36_streambuf DB 01H
__D3F4E7C5_xlocnum DB 01H
__439EEBD1_ios DB 01H
__5E635B16_ostream DB 01H
__3DB36E2C_istream DB 01H
__55AF793C_iostream DB 01H
__3347223C_winpackagefamily@h DB 01H
__F5B671E4_winapifamily@h DB 01H
__6866F092_sdkddkver@h DB 01H
__F2721980_excpt@h DB 01H
__6FD1C511_stdarg@h DB 01H
__4114BAD5_specstrings_undef@h DB 01H
__50F9AEDC_specstrings_strict@h DB 01H
__BEFC0098_sdv_driverspecs@h DB 01H
__39A39701_driverspecs@h DB 01H
__B4D8BDAA_specstrings@h DB 01H
__B6CCE7CD_kernelspecs@h DB 01H
__201B1099_basetsd@h DB 01H
__8C99318D_guiddef@h DB 01H
__A3CAA675_pshpack4@h DB 01H
__2611E9B9_poppack@h DB 01H
__A747DAC7_pshpack2@h DB 01H
__AAD05F11_pshpack8@h DB 01H
__A501649E_pshpack1@h DB 01H
__0E9D9C0E_apiset@h DB 01H
__F9851A06_ktmtypes@h DB 01H
__9DA2B69E_winnt@h DB 01H
__E9AED855_minwindef@h DB 01H
__9668718B_windef@h DB 01H
__B47C9622_apisetcconv@h DB 01H
__77F4CE3E_minwinbase@h DB 01H
__42CF8FD5_apiquery2@h DB 01H
__A6C51434_processenv@h DB 01H
__415D7145_fileapi@h DB 01H
__A7316A9B_fileapifromapp@h DB 01H
__A0359A2D_debugapi@h DB 01H
__28BE1226_utilapiset@h DB 01H
__6933B394_handleapi@h DB 01H
__57F09DF9_errhandlingapi@h DB 01H
__E0622DF9_fibersapi@h DB 01H
__D531F6AB_namedpipeapi@h DB 01H
__ADD82BB4_profileapi@h DB 01H
__ECFC4D70_heapapi@h DB 01H
__4F41815B_ioapiset@h DB 01H
__8D44BFB7_synchapi@h DB 01H
__8CAEC090_interlockedapi@h DB 01H
__8ABF54F4_processthreadsapi@h DB 01H
__1462A586_sysinfoapi@h DB 01H
__369DBA4C_memoryapi@h DB 01H
__02D65571_enclaveapi@h DB 01H
__50387E19_threadpoollegacyapiset@h DB 01H
__C40195AA_threadpoolapiset@h DB 01H
__792B5764_jobapi@h DB 01H
__BAD0D5EB_jobapi2@h DB 01H
__C6FE0B21_wow64apiset@h DB 01H
__94EE79C1_libloaderapi@h DB 01H
__E203BDE6_securitybaseapi@h DB 01H
__9590F1DC_namespaceapi@h DB 01H
__0F4602F6_systemtopologyapi@h DB 01H
__B1B3B677_processtopologyapi@h DB 01H
__7DD200C2_securityappcontainer@h DB 01H
__130664A2_realtimeapiset@h DB 01H
__A8C6672F_winerror@h DB 01H
__A093DD28_timezoneapi@h DB 01H
__6BD3506C_winbase@h DB 01H
__DABCB3B7_wingdi@h DB 01H
__CD8F5E54_tvout@h DB 01H
__033B1B1B_winuser@h DB 01H
__F8663FCA_datetimeapi@h DB 01H
__03A9DF8F_winnls@h DB 01H
__CB7A78CC_stringapiset@h DB 01H
__3F149E59_wincontypes@h DB 01H
__7CC6F8F3_consoleapi@h DB 01H
__D4BE3EA3_consoleapi2@h DB 01H
__D57C5494_consoleapi3@h DB 01H
__FD7284F3_wincon@h DB 01H
__2EBE7A74_verrsrc@h DB 01H
__2FF32671_winver@h DB 01H
__E384C5B4_reason@h DB 01H
__C09EE12A_winreg@h DB 01H
__F1A080AC_wnnc@h DB 01H
__C375DB87_winnetwk@h DB 01H
__F202032E_cderr@h DB 01H
__96C2AB0F_dde@h DB 01H
__005A4F24_ddeml@h DB 01H
__8B7EE07A_dlgs@h DB 01H
__0D44BE7C_lzexpand@h DB 01H
__7DBDB4C6_mmsyscom@h DB 01H
__DE89C4CA_mciapi@h DB 01H
__42D37885_mmiscapi@h DB 01H
__6DE6FF2A_mmiscapi2@h DB 01H
__FF70E3D7_playsoundapi@h DB 01H
__F9747FEC_mmeapi@h DB 01H
__651C1006_timeapi@h DB 01H
__60A046E1_joystickapi@h DB 01H
__C0C01F30_mmsystem@h DB 01H
__A366D611_nb30@h DB 01H
__2CD5644B_rpcdcep@h DB 01H
__B77D54A9_rpcdce@h DB 01H
__1C5A7A47_rpcnsi@h DB 01H
__71643EA7_rpcnterr@h DB 01H
__38122515_rpcasync@h DB 01H
__DEF407DB_rpc@h DB 01H
__064CC72C_shellapi@h DB 01H
__6AB78C00_winperf@h DB 01H
__683BB200_inaddr@h DB 01H
__46EE45A6_winsock@h DB 01H
__924250EA_bcrypt@h DB 01H
__7D79DD11_ncrypt@h DB 01H
__C925E4C0_dpapi@h DB 01H
__CE4C9021_wincrypt@h DB 01H
__1BC40EFA_winefs@h DB 01H
__6BCC8C1A_rpcnsip@h DB 01H
__C065EC3F_rpcsal@h DB 01H
__7973C144_rpcndr@h DB 01H
__B58B1953_wtypesbase@h DB 01H
__013FEE7F_wtypes@h DB 01H
__62733496_winioctl@h DB 01H
__B9109027_winsmcrd@h DB 01H
__87A76A69_winscard@h DB 01H
__8C0F76A7_prsht@h DB 01H
__11B57AC7_winspool@h DB 01H
__DBA05CC8_unknwnbase@h DB 01H
__D99DEA84_objidlbase@h DB 01H
__A2F85269_cguid@h DB 01H
__A856EBD7_combaseapi@h DB 01H
__47009772_unknwn@h DB 01H
__558FF34F_objidl@h DB 01H
__EA6828E6_oaidl@h DB 01H
__DD5918D8_propidlbase@h DB 01H
__A0E2593F_coml2api@h DB 01H
__F4E63AC7_oleidl@h DB 01H
__0E8757FF_servprov@h DB 01H
__13616BE7_msxml@h DB 01H
__287654D0_urlmon@h DB 01H
__3465A794_propidl@h DB 01H
__D5EE8840_objbase@h DB 01H
__B5981418_oleauto@h DB 01H
__3AE83FC5_ole2@h DB 01H
__5F30FE09_commdlg@h DB 01H
__DD9DD587_stralign@h DB 01H
__B85B9837_winsvc@h DB 01H
__12FBC1E4_mcx@h DB 01H
__BC6D10F5_ime_cmodes@h DB 01H
__1D49718C_imm@h DB 01H
__1782C726_Windows@h DB 01H
__82641940_Task1@2_FIS@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?__empty_global_delete@@YAXPAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPAXI@Z		; __empty_global_delete
PUBLIC	?code_cave@@YAXKKK@Z				; code_cave
PUBLIC	??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z ; std::endl<char,std::char_traits<char> >
PUBLIC	?file_open@@YAHPAU_iobuf@@@Z			; file_open
PUBLIC	?retrive_dos_header@@YAPAU_IMAGE_DOS_HEADER@@PAU_iobuf@@@Z ; retrive_dos_header
PUBLIC	?retrieve_nt_headers@@YAPAU_IMAGE_NT_HEADERS@@PAU_iobuf@@PAU_IMAGE_DOS_HEADER@@@Z ; retrieve_nt_headers
PUBLIC	?message_box@@YAKXZ				; message_box
PUBLIC	?shell_creation@@YAXPAU_IMAGE_NT_HEADERS@@K@Z	; shell_creation
PUBLIC	_main
PUBLIC	__JustMyCode_Default
PUBLIC	??_C@_07KGMMFLDN@Warning@			; `string'
PUBLIC	??_C@_0BB@NHNDFKDA@You?5are?5infected@		; `string'
PUBLIC	??_C@_0FD@PHBHDNMB@C?3?$AIenign?$AIenign?$ABaa177b92c99b9458@ ; `string'
PUBLIC	??_C@_02JDPG@rb@				; `string'
EXTRN	__imp__fopen_s:PROC
EXTRN	__imp__fread:PROC
EXTRN	__imp__fseek:PROC
EXTRN	__imp_?widen@?$basic_ios@DU?$char_traits@D@std@@@std@@QBEDD@Z:PROC
EXTRN	__imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@P6AAAV01@AAV01@@Z@Z:PROC
EXTRN	__imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@K@Z:PROC
EXTRN	__imp_?put@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@D@Z:PROC
EXTRN	__imp_?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@XZ:PROC
EXTRN	__imp__MessageBoxW@16:PROC
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	@__CheckForDebuggerJustMyCode@4:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	_memset:PROC
EXTRN	__imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A:BYTE
EXTRN	___security_cookie:DWORD
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT ??_C@_02JDPG@rb@
CONST	SEGMENT
??_C@_02JDPG@rb@ DB 'rb', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0FD@PHBHDNMB@C?3?$AIenign?$AIenign?$ABaa177b92c99b9458@
CONST	SEGMENT
??_C@_0FD@PHBHDNMB@C?3?$AIenign?$AIenign?$ABaa177b92c99b9458@ DB 'C:', 08H
	DB	'enign', 08H, 'enign', 01H, 'aa177b92c99b9458b270907d65d5687af'
	DB	'48385fbbf42c3aef9b69d61d284721.exe', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0BB@NHNDFKDA@You?5are?5infected@
CONST	SEGMENT
??_C@_0BB@NHNDFKDA@You?5are?5infected@ DB 'You are infected', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_07KGMMFLDN@Warning@
CONST	SEGMENT
??_C@_07KGMMFLDN@Warning@ DB 'Warning', 00H		; `string'
CONST	ENDS
;	COMDAT voltbl
voltbl	SEGMENT
_volmd	DW	025H
	DW	014fH
voltbl	ENDS
;	COMDAT voltbl
voltbl	SEGMENT
_volmd	DB	022H
	DB	083H
voltbl	ENDS
;	COMDAT voltbl
voltbl	SEGMENT
_volmd	DB	022H
	DB	07eH
voltbl	ENDS
;	COMDAT voltbl
voltbl	SEGMENT
_volmd	DB	022H
	DB	09aH
voltbl	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	push	ebp
	mov	ebp, esp
	pop	ebp
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT _main
_TEXT	SEGMENT
tv79 = -533						; size = 1
_flag$ = -333						; size = 1
_image_nt_headers$ = -324				; size = 4
_dos_header$ = -312					; size = 4
_message$ = -300					; size = 4
_target_file$ = -288					; size = 4
_file_name$ = -276					; size = 255
_MAX_FILEPATH$ = -12					; size = 4
__$ArrayPad$ = -4					; size = 4
_argc$ = 8						; size = 4
_argv$ = 12						; size = 4
_main	PROC						; COMDAT
; File C:\Users\maste\source\repos\Task1.2_FIS\Task1.2_FIS.cpp
; Line 87
	push	ebp
	mov	ebp, esp
	sub	esp, 536				; 00000218H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-344]
	mov	ecx, 86					; 00000056H
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __82641940_Task1@2_FIS@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 89
	mov	DWORD PTR _MAX_FILEPATH$[ebp], 255	; 000000ffH
; Line 90
	mov	ecx, 20					; 00000014H
	mov	esi, OFFSET ??_C@_0FD@PHBHDNMB@C?3?$AIenign?$AIenign?$ABaa177b92c99b9458@
	lea	edi, DWORD PTR _file_name$[ebp]
	rep movsd
	movsw
	movsb
	push	172					; 000000acH
	push	0
	lea	eax, DWORD PTR _file_name$[ebp+83]
	push	eax
	call	_memset
	add	esp, 12					; 0000000cH
; Line 92
	mov	esi, esp
	push	OFFSET ??_C@_02JDPG@rb@
	lea	eax, DWORD PTR _file_name$[ebp]
	push	eax
	lea	ecx, DWORD PTR _target_file$[ebp]
	push	ecx
	call	DWORD PTR __imp__fopen_s
	add	esp, 12					; 0000000cH
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 93
	cmp	DWORD PTR _target_file$[ebp], 0
	jne	SHORT $LN2@main
; Line 94
	or	eax, -1
	jmp	$LN1@main
$LN2@main:
; Line 97
	mov	DWORD PTR _message$[ebp], 0
; Line 98
	mov	DWORD PTR _dos_header$[ebp], 0
; Line 99
	mov	DWORD PTR _image_nt_headers$[ebp], 0
; Line 102
	mov	eax, DWORD PTR _target_file$[ebp]
	push	eax
	call	?file_open@@YAHPAU_iobuf@@@Z		; file_open
	add	esp, 4
	test	eax, eax
	je	SHORT $LN4@main
	mov	BYTE PTR tv79[ebp], 1
	jmp	SHORT $LN5@main
$LN4@main:
	mov	BYTE PTR tv79[ebp], 0
$LN5@main:
	mov	cl, BYTE PTR tv79[ebp]
	mov	BYTE PTR _flag$[ebp], cl
; Line 105
	mov	eax, DWORD PTR _target_file$[ebp]
	push	eax
	call	?retrive_dos_header@@YAPAU_IMAGE_DOS_HEADER@@PAU_iobuf@@@Z ; retrive_dos_header
	add	esp, 4
	mov	DWORD PTR _dos_header$[ebp], eax
; Line 106
	mov	eax, DWORD PTR _dos_header$[ebp]
	push	eax
	mov	ecx, DWORD PTR _target_file$[ebp]
	push	ecx
	call	?retrieve_nt_headers@@YAPAU_IMAGE_NT_HEADERS@@PAU_iobuf@@PAU_IMAGE_DOS_HEADER@@@Z ; retrieve_nt_headers
	add	esp, 8
	mov	DWORD PTR _image_nt_headers$[ebp], eax
; Line 109
	call	?message_box@@YAKXZ			; message_box
	mov	DWORD PTR _message$[ebp], eax
; Line 110
	mov	eax, DWORD PTR _message$[ebp]
	push	eax
	mov	ecx, DWORD PTR _image_nt_headers$[ebp]
	push	ecx
	call	?shell_creation@@YAXPAU_IMAGE_NT_HEADERS@@K@Z ; shell_creation
	add	esp, 8
; Line 112
	xor	eax, eax
$LN1@main:
; Line 113
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN9@main
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 536				; 00000218H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	2
$LN9@main:
	DD	2
	DD	$LN8@main
$LN8@main:
	DD	-276					; fffffeecH
	DD	255					; 000000ffH
	DD	$LN6@main
	DD	-288					; fffffee0H
	DD	4
	DD	$LN7@main
$LN7@main:
	DB	116					; 00000074H
	DB	97					; 00000061H
	DB	114					; 00000072H
	DB	103					; 00000067H
	DB	101					; 00000065H
	DB	116					; 00000074H
	DB	95					; 0000005fH
	DB	102					; 00000066H
	DB	105					; 00000069H
	DB	108					; 0000006cH
	DB	101					; 00000065H
	DB	0
$LN6@main:
	DB	102					; 00000066H
	DB	105					; 00000069H
	DB	108					; 0000006cH
	DB	101					; 00000065H
	DB	95					; 0000005fH
	DB	110					; 0000006eH
	DB	97					; 00000061H
	DB	109					; 0000006dH
	DB	101					; 00000065H
	DB	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?shell_creation@@YAXPAU_IMAGE_NT_HEADERS@@K@Z
_TEXT	SEGMENT
_difference_btw_iohs$ = -20				; size = 4
_start_pt$ = -8						; size = 4
_nt_headers$ = 8					; size = 4
_message$ = 12						; size = 4
?shell_creation@@YAXPAU_IMAGE_NT_HEADERS@@K@Z PROC	; shell_creation, COMDAT
; File C:\Users\maste\source\repos\Task1.2_FIS\Task1.2_FIS.cpp
; Line 77
	push	ebp
	mov	ebp, esp
	sub	esp, 216				; 000000d8H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-24]
	mov	ecx, 6
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __82641940_Task1@2_FIS@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 79
	mov	eax, DWORD PTR _nt_headers$[ebp]
	mov	ecx, DWORD PTR [eax+60]
	mov	DWORD PTR _start_pt$[ebp], ecx
; Line 80
	mov	eax, DWORD PTR _nt_headers$[ebp]
	mov	ecx, DWORD PTR _nt_headers$[ebp]
	mov	edx, DWORD PTR [eax+56]
	sub	edx, DWORD PTR [ecx+60]
	mov	DWORD PTR _difference_btw_iohs$[ebp], edx
; Line 83
	mov	eax, DWORD PTR _message$[ebp]
	push	eax
	mov	ecx, DWORD PTR _difference_btw_iohs$[ebp]
	push	ecx
	mov	edx, DWORD PTR _start_pt$[ebp]
	push	edx
	call	?code_cave@@YAXKKK@Z			; code_cave
	add	esp, 12					; 0000000cH
; Line 84
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?shell_creation@@YAXPAU_IMAGE_NT_HEADERS@@K@Z ENDP	; shell_creation
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?message_box@@YAKXZ
_TEXT	SEGMENT
_msg$ = -8						; size = 4
?message_box@@YAKXZ PROC				; message_box, COMDAT
; File C:\Users\maste\source\repos\Task1.2_FIS\Task1.2_FIS.cpp
; Line 72
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-12]
	mov	ecx, 3
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __82641940_Task1@2_FIS@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 73
	mov	esi, esp
	push	0
	push	OFFSET ??_C@_07KGMMFLDN@Warning@
	push	OFFSET ??_C@_0BB@NHNDFKDA@You?5are?5infected@
	push	0
	call	DWORD PTR __imp__MessageBoxW@16
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _msg$[ebp], eax
; Line 74
	mov	eax, DWORD PTR _msg$[ebp]
; Line 75
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?message_box@@YAKXZ ENDP				; message_box
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?retrieve_nt_headers@@YAPAU_IMAGE_NT_HEADERS@@PAU_iobuf@@PAU_IMAGE_DOS_HEADER@@@Z
_TEXT	SEGMENT
_nt_headers$ = -12					; size = 4
__$ArrayPad$ = -4					; size = 4
_pe_file$ = 8						; size = 4
_dos_header$ = 12					; size = 4
?retrieve_nt_headers@@YAPAU_IMAGE_NT_HEADERS@@PAU_iobuf@@PAU_IMAGE_DOS_HEADER@@@Z PROC ; retrieve_nt_headers, COMDAT
; File C:\Users\maste\source\repos\Task1.2_FIS\Task1.2_FIS.cpp
; Line 59
	push	ebp
	mov	ebp, esp
	sub	esp, 208				; 000000d0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-16]
	mov	ecx, 4
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __82641940_Task1@2_FIS@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 64
	mov	esi, esp
	push	0
	mov	eax, DWORD PTR _dos_header$[ebp]
	mov	ecx, DWORD PTR [eax+60]
	push	ecx
	mov	edx, DWORD PTR _pe_file$[ebp]
	push	edx
	call	DWORD PTR __imp__fseek
	add	esp, 12					; 0000000cH
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 65
	mov	esi, esp
	mov	eax, DWORD PTR _pe_file$[ebp]
	push	eax
	push	1
	push	4
	lea	ecx, DWORD PTR _nt_headers$[ebp]
	push	ecx
	call	DWORD PTR __imp__fread
	add	esp, 16					; 00000010H
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 68
	mov	eax, DWORD PTR _nt_headers$[ebp]
; Line 69
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN5@retrieve_n
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 208				; 000000d0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	2
$LN5@retrieve_n:
	DD	1
	DD	$LN4@retrieve_n
$LN4@retrieve_n:
	DD	-12					; fffffff4H
	DD	4
	DD	$LN3@retrieve_n
$LN3@retrieve_n:
	DB	110					; 0000006eH
	DB	116					; 00000074H
	DB	95					; 0000005fH
	DB	104					; 00000068H
	DB	101					; 00000065H
	DB	97					; 00000061H
	DB	100					; 00000064H
	DB	101					; 00000065H
	DB	114					; 00000072H
	DB	115					; 00000073H
	DB	0
?retrieve_nt_headers@@YAPAU_IMAGE_NT_HEADERS@@PAU_iobuf@@PAU_IMAGE_DOS_HEADER@@@Z ENDP ; retrieve_nt_headers
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?retrive_dos_header@@YAPAU_IMAGE_DOS_HEADER@@PAU_iobuf@@@Z
_TEXT	SEGMENT
_dos_header$ = -12					; size = 4
__$ArrayPad$ = -4					; size = 4
_pe_file$ = 8						; size = 4
?retrive_dos_header@@YAPAU_IMAGE_DOS_HEADER@@PAU_iobuf@@@Z PROC ; retrive_dos_header, COMDAT
; File C:\Users\maste\source\repos\Task1.2_FIS\Task1.2_FIS.cpp
; Line 47
	push	ebp
	mov	ebp, esp
	sub	esp, 208				; 000000d0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-16]
	mov	ecx, 4
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __82641940_Task1@2_FIS@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 52
	mov	esi, esp
	push	0
	push	0
	mov	eax, DWORD PTR _pe_file$[ebp]
	push	eax
	call	DWORD PTR __imp__fseek
	add	esp, 12					; 0000000cH
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 53
	mov	esi, esp
	mov	eax, DWORD PTR _pe_file$[ebp]
	push	eax
	push	1
	push	4
	lea	ecx, DWORD PTR _dos_header$[ebp]
	push	ecx
	call	DWORD PTR __imp__fread
	add	esp, 16					; 00000010H
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 56
	mov	eax, DWORD PTR _dos_header$[ebp]
; Line 57
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN5@retrive_do
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 208				; 000000d0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	3
$LN5@retrive_do:
	DD	1
	DD	$LN4@retrive_do
$LN4@retrive_do:
	DD	-12					; fffffff4H
	DD	4
	DD	$LN3@retrive_do
$LN3@retrive_do:
	DB	100					; 00000064H
	DB	111					; 0000006fH
	DB	115					; 00000073H
	DB	95					; 0000005fH
	DB	104					; 00000068H
	DB	101					; 00000065H
	DB	97					; 00000061H
	DB	100					; 00000064H
	DB	101					; 00000065H
	DB	114					; 00000072H
	DB	0
?retrive_dos_header@@YAPAU_IMAGE_DOS_HEADER@@PAU_iobuf@@@Z ENDP ; retrive_dos_header
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?file_open@@YAHPAU_iobuf@@@Z
_TEXT	SEGMENT
_is_pe_file$ = -24					; size = 4
_tmp_dos_header$ = -12					; size = 4
__$ArrayPad$ = -4					; size = 4
_target_file$ = 8					; size = 4
?file_open@@YAHPAU_iobuf@@@Z PROC			; file_open, COMDAT
; File C:\Users\maste\source\repos\Task1.2_FIS\Task1.2_FIS.cpp
; Line 30
	push	ebp
	mov	ebp, esp
	sub	esp, 220				; 000000dcH
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-28]
	mov	ecx, 7
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	mov	ecx, OFFSET __82641940_Task1@2_FIS@cpp
	call	@__CheckForDebuggerJustMyCode@4
; Line 33
	mov	DWORD PTR _is_pe_file$[ebp], 0
; Line 36
	mov	esi, esp
	push	0
	push	0
	mov	eax, DWORD PTR _target_file$[ebp]
	push	eax
	call	DWORD PTR __imp__fseek
	add	esp, 12					; 0000000cH
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 37
	mov	esi, esp
	mov	eax, DWORD PTR _target_file$[ebp]
	push	eax
	push	1
	push	4
	lea	ecx, DWORD PTR _tmp_dos_header$[ebp]
	push	ecx
	call	DWORD PTR __imp__fread
	add	esp, 16					; 00000010H
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 40
	mov	eax, DWORD PTR _tmp_dos_header$[ebp]
	movzx	ecx, WORD PTR [eax]
	cmp	ecx, 23117				; 00005a4dH
	je	SHORT $LN2@file_open
; Line 41
	mov	DWORD PTR _is_pe_file$[ebp], -1
$LN2@file_open:
; Line 44
	mov	eax, DWORD PTR _is_pe_file$[ebp]
; Line 45
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN6@file_open
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 220				; 000000dcH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	3
$LN6@file_open:
	DD	1
	DD	$LN5@file_open
$LN5@file_open:
	DD	-12					; fffffff4H
	DD	4
	DD	$LN4@file_open
$LN4@file_open:
	DB	116					; 00000074H
	DB	109					; 0000006dH
	DB	112					; 00000070H
	DB	95					; 0000005fH
	DB	100					; 00000064H
	DB	111					; 0000006fH
	DB	115					; 00000073H
	DB	95					; 0000005fH
	DB	104					; 00000068H
	DB	101					; 00000065H
	DB	97					; 00000061H
	DB	100					; 00000064H
	DB	101					; 00000065H
	DB	114					; 00000072H
	DB	0
?file_open@@YAHPAU_iobuf@@@Z ENDP			; file_open
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z
_TEXT	SEGMENT
__Ostr$ = 8						; size = 4
??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z PROC ; std::endl<char,std::char_traits<char> >, COMDAT
; File C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\include\ostream
; Line 1005
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	mov	edi, ebp
	xor	ecx, ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __5E635B16_ostream
	call	@__CheckForDebuggerJustMyCode@4
; Line 1006
	mov	esi, esp
	push	10					; 0000000aH
	mov	eax, DWORD PTR __Ostr$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	edx, DWORD PTR __Ostr$[ebp]
	add	edx, DWORD PTR [ecx+4]
	mov	ecx, edx
	call	DWORD PTR __imp_?widen@?$basic_ios@DU?$char_traits@D@std@@@std@@QBEDD@Z
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	esi, esp
	movzx	eax, al
	push	eax
	mov	ecx, DWORD PTR __Ostr$[ebp]
	call	DWORD PTR __imp_?put@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@D@Z
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 1007
	mov	esi, esp
	mov	ecx, DWORD PTR __Ostr$[ebp]
	call	DWORD PTR __imp_?flush@?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV12@XZ
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 1008
	mov	eax, DWORD PTR __Ostr$[ebp]
; Line 1009
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z ENDP ; std::endl<char,std::char_traits<char> >
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?code_cave@@YAXKKK@Z
_TEXT	SEGMENT
_start_pt$ = 8						; size = 4
_difference_between_iohs$ = 12				; size = 4
_message$ = 16						; size = 4
?code_cave@@YAXKKK@Z PROC				; code_cave, COMDAT
; File C:\Users\maste\source\repos\Task1.2_FIS\Task1.2_FIS.cpp
; Line 11
	pop	DWORD PTR _start_pt$[ebp]
; Line 12
	mov	DWORD PTR _message$[ebp], edx
; Line 13
	pushad
; Line 14
	pushfd
; Line 18
	mov	esi, esp
	push	OFFSET ??$endl@DU?$char_traits@D@std@@@std@@YAAAV?$basic_ostream@DU?$char_traits@D@std@@@0@AAV10@@Z ; std::endl<char,std::char_traits<char> >
	mov	edi, esp
	mov	eax, DWORD PTR _message$[ebp]
	push	eax
	mov	ecx, DWORD PTR __imp_?cout@std@@3V?$basic_ostream@DU?$char_traits@D@std@@@1@A
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@K@Z
	cmp	edi, esp
	call	__RTC_CheckEsp
	mov	ecx, eax
	call	DWORD PTR __imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QAEAAV01@P6AAAV01@AAV01@@Z@Z
	cmp	esi, esp
	call	__RTC_CheckEsp
; Line 22
	popfd
; Line 23
	popad
; Line 24
	cmp	edx, 5632				; 00001600H
; Line 25
	push	DWORD PTR _start_pt$[ebp]
; Line 26
	ret	0
?code_cave@@YAXKKK@Z ENDP				; code_cave
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?__empty_global_delete@@YAXPAXI@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
___formal$ = 12						; size = 4
?__empty_global_delete@@YAXPAXI@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\maste\source\repos\Task1.2_FIS\Task1.2_FIS.cpp
; Line 116
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	mov	edi, ebp
	xor	ecx, ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __82641940_Task1@2_FIS@cpp
	call	@__CheckForDebuggerJustMyCode@4
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAXI@Z ENDP			; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
;	COMDAT ?__empty_global_delete@@YAXPAX@Z
_TEXT	SEGMENT
___formal$ = 8						; size = 4
?__empty_global_delete@@YAXPAX@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\maste\source\repos\Task1.2_FIS\Task1.2_FIS.cpp
; Line 116
	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	mov	edi, ebp
	xor	ecx, ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	mov	ecx, OFFSET __82641940_Task1@2_FIS@cpp
	call	@__CheckForDebuggerJustMyCode@4
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?__empty_global_delete@@YAXPAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
